using System.Collections.Generic;
using ReportPortalNUnitLog4netClient.Models;
using ReportPortalNUnitLog4netClient.Models.Api;

namespace ReportPortalNUnitLog4netClient.Factory
{
    public static class RpDashboardFactory
    {
        public static RpDashboard GetRpDashboard(string launchName, string dashboardName, Attribute cumulative = null, Attribute healthCheck = null)
        {
            var filter = RpFilterFactory.ByLaunchName(launchName);
            var dashboard = new Dashboard
            {
                Name = dashboardName,
                Description = "Autogenerated dashboard"
            };

            var widgets = new List<Widget>
            {
                RpWidgetFactory.LastLaunchStatistics(),
                RpWidgetFactory.LaunchResultTrend(),
            };

            if (cumulative != null)
            {
                widgets.Add(RpWidgetFactory.CumulativeTrend(cumulative.Key, cumulative.Value));
            }

            var widgetsAdditional = new[]
            {
                RpWidgetFactory.TestCasesTrend(),
                RpWidgetFactory.LaunchesDurationChart(),
                RpWidgetFactory.FailedCasesTrend(),
                RpWidgetFactory.UniqueBugTable(),
            };

            widgets.AddRange(widgetsAdditional);

            if (healthCheck != null)
            {
                widgets.Add(RpWidgetFactory.ComponentHealthCheck(healthCheck.Key, healthCheck.Value));
            }

            return new RpDashboard(filter, dashboard, widgets);
        }
    }
}
