using System.Collections.Generic;
using ReportPortalNUnitLog4netClient.Models;
using ReportPortalNUnitLog4netClient.Models.Api;

namespace ReportPortalNUnitLog4netClient.Factory
{
    public static class RpDashboardFactory
    {
        public static RpDashboard GetRpDashboard(string launchName, string dashboardName, string keyOneForCumulative, string keyTwoForCumulative)
        {
            var filter = RpFilterFactory.ByLaunchName(launchName);
            var dashboard = new Dashboard
            {
                Name = dashboardName,
                Description = "Autogenerated dashboard"
            };

            var widgets = new List<Widget>
            {
                RpWidgetFactory.LastLaunchStatistics(),
                RpWidgetFactory.LaunchResultTrend(),
                RpWidgetFactory.CumulativeTrend(keyOneForCumulative, keyTwoForCumulative),
                RpWidgetFactory.TestCasesTrend(),
                RpWidgetFactory.LaunchesDurationChart(),
                RpWidgetFactory.FailedCasesTrend(),
            };
            return new RpDashboard(filter, dashboard, widgets);
        }
    }
}
